### ISSUE TITLE
IN: Amazon S3

### ISSUE THREAD

**Issue by dproc96** [hatchways/team-santorini#19]
Integrate route with frontend component to upload images and return the url

**Comment by ahmed-belhadj** [comment]
https://github.com/hatchways/team-santorini/blob/d583316a805c60e3702bb9f99853b269bd42bce7/client/src/context/useAuthContext.tsx#L38

**Comment by ahmed-belhadj** [comment]
Completed in part by #35 component. Next steps: need Cloudinary URL stored in AuthContext to be saved to MongoDB.
